In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
from sklearn.model_selection import train_test_split

In [37]:
df = pd.read_csv(r'C:\Users\student\.cache\kagglehub\datasets\volodymyrgavrysh\heart-disease\versions\1\heart.csv') 
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [38]:
X = df.drop("target", axis=1)
y = df["target"]       
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [39]:
import numpy as np

def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2)**2))

In [40]:
from collections import Counter

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train

    def predict(self, X_test):
        predictions = [self._predict_single_point(point) for point in X_test]
        return np.array(predictions)

    def _predict_single_point(self, test_point):
        distances = [euclidean_distance(test_point, train_point) for train_point in self.X_train]

        k_nearest_indices = np.argsort(distances)[:self.k]


        k_nearest_labels = [self.y_train[i] for i in k_nearest_indices]

        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]

In [41]:
# X_train = np.array([[1, 1], [1, 2], [2, 2], [5, 8], [6, 8], [7, 9]])
# y_train = np.array([0, 0, 0, 1, 1, 1]) 

# X_test = np.array([[3, 4], [6, 7]])

# knn_model = KNN(k=3)
# knn_model.fit(X_train, y_train)

# predictions = knn_model.predict(X_test)
# print(f"Predictions for test points: {predictions}")

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
knn_model = KNN(k=5)
knn_model.fit(X_train,y_train)
predictions = knn_model.predict(X_test)
print("Predictions for test poin